data:
  batch_size: 2000
  num_workers: 0
  pin_mem: true
#  spec_path: ../../data/with_label/lma_good/refl_is_tree.csv
  spec_path:
    train: ../../data/with_label/lma_good/refl_not_tree.csv
    test: ../../data/with_label/lma_good/refl_is_tree.csv
  split_ratio:
    - 0.7
    - 0.3
  tasks:
    - LMA
#  trait_path: ../../data/with_label/lma_good/trait_is_tree.csv
  trait_path:
    train: ../../data/with_label/lma_good/trait_not_tree.csv
    test: ../../data/with_label/lma_good/trait_is_tree.csv
meta:
  n_components: 5
  output_dims:
    LMA: 1
  seed: 42
log:
  save_dir: false
  tag: is_tree