data:
  batch_size: 2000
  num_workers: 0
  pin_mem: true
  spec_path: C:/file/Research/projects/TCAF/data/with_label/AllRefl.csv
#  spec_path: C:/file/Research/projects/TCAF/data/demo/hs_refl.csv
#  spec_path: C:/file/Research/projects/TCAF/data/demo/hs_refl.csv
  split_ratio:
    - 0.7
    - 0.3
  tasks:
    - LMA
  trait_path: C:/file/Research/projects/TCAF/data/with_label/AllTraitsFilted.csv
#  trait_path: C:/file/Research/projects/TCAF/data/demo/hs_trait.csv
#  trait_path: C:/file/Research/projects/TCAF/data/demo/hs_trait.csv
meta:
  n_components: 5
  seed: 42
log:
  save_dir: C:/file/Research/projects/TCAF/fig/plsr/plsr_lma.png