data:
  batch_size: 1200
  num_workers: 0
  pin_mem: true
#  spec_path: ../../data/with_label/AllRefl.csv
#  spec_path: ../../data/demo/hs_refl_demo.csv
#  spec_path: ../../data/demo/hs_refl.csv
  spec_path: ../../data/demo/cabo_refl.csv
#  spec_path: ../../data/demo/165_refl.csv
  split_ratio:
    - 0.7
    - 0.3
  tasks:
    - LMA
#  trait_path: ../../data/with_label/AllTraitsFilted.csv
#  trait_path: ../../data/demo/hs_trait_demo.csv
#  trait_path: ../../data/demo/hs_trait.csv
  trait_path: ../../data/demo/cabo_trait.csv
#  trait_path: ../../data/demo/165_trait.csv
logging:
  folder: checkpoints/
meta:
  preprocess: manual
  proj_type: conv
  pe_type: learnable
  model_size: base
  dataset_name: fresh
  pred_type: complete
  output_dims:
    LMA: 1
    CHL: 1
    Type: 4
  load_processor: true
  read_checkpoint: manual_conv_learnable_base_fresh_complete_cabo_lma-latest.pth.tar
  patch_size: 30
  pred_emb_dim: 96
  pred_depth: 2
  seed: 42